### PR TITLE
Normalization of the the JSX syntax vs React

### PR DESCRIPTION
**Pull request by SeanJM**
To remove some of the gotchas from people coming from React, I modified the JSX syntax to be similar to that of React with the exception of 'class' which I think is a better choice than 'className'

instead of writing `on-click` you would write `onclick` or `onClick`, intead of writing `hook-fish` you would write `hookFish|hookFish` etc.

### CODE REVIEW

**Comment by SeanJM** [comment]
I can assure you, all tests pass.

**Comment by SeanJM** [comment]
I'll have to add the xlink support.

**Comment by SeanJM** [comment]
AHH the updated version. I did not run the tests after the merge... OK!

**Comment by yyx990803** [comment]
Hi @SeanJM, although I appreciate the effort, I can't merge this because:

1. JSX is not React-specific, and I don't see a particular reason to mimic React JSX.

2. This is a breaking change, and a pretty big one. There are already many users using this plugin in their applications. I don't think the change is worth making them rewrite their code.

I think it's better off to just create a fork and publish it as a separate plugin.

Finally a suggestion when you submit PRs in the future: if you want to propose a big breaking change, make sure to first open an issue and discuss it with the author. When you directly open a big PR like this, it's unlikely to be accepted and very difficult to refactor into something mergeable.

**Comment by SeanJM** [comment]
This is odd,  just closed at the same time. Interesting.

1. It’s not necessarily mimicking React. I see it as unifying two ways of doing things to reduce cognitive overhead.
2. It is a breaking change.

I’ll probably delete it, I don’t have time to maintain this. Anyways. Good luck Evan.

Sean

**Pull request closed without merging**
