### PR TITLE
feat: custom jsx, fixed #55

### LINKED ISSUE #55: Change 'identifier' to 'this.$createElement'
I noticed that render function is called by the current vm (See [vue.runtime.common.js#L2216](https://github.com/vuejs/vue/blob/dev/dist/vue.runtime.common.js#L2216)). Maybe we can replace `h` to `this.$createElement`? We can remove "ugly" `h`.

I can submit PR if you agree.

### PR DESCRIPTION
**Pull request by QingWei-Li**
@yyx990803 @nickmessing Please review it. 😊

### CODE REVIEW

**Comment by QingWei-Li** [comment]
@nickmessing  We can provide an alias to reduce the size. For example

```js
Vue.use(function (Vue) {
  Vue.prototype.$h = function () {
    return this.$createElement.apply(this, arguments)
  }
})
```

``` json
{
  "presets": ["es2015"],
  "plugins": [
      ["transform-vue-jsx", { "jsx": "this.$h" }]
  ]
}
```

**Comment by QingWei-Li** [comment]
I made a mistake. 😱  If we write `arr.map(i => <li>{ i }</li>)`, It will be compiled to

```js
this.$createElement(
  'ul',
  null,
  [arr.map(function (i) {
    return this.$createElement(
      'li',
      null,
      [i]
    );
  })]
);
```

Looks like I did not solve the issue 😂

**Comment by yyx990803** [comment]
Maybe instead we can try to inject `const h = this.$createElement` automatically into functions that contain JSX?

**Comment by nickmessing** [comment]
@yyx990803, that actually sounds like a Way better solution, @QingWei-Li, I guess you can close this PR, do you want to do that or I should?

**Comment by QingWei-Li** [comment]
@nickmessing Yes, I will close this PR.

**Pull request closed without merging**
