### PR TITLE
Automatically add const h = this.$createElement in methods.

### PR DESCRIPTION
**Pull request by nickmessing**
@yyx990803, @QingWei-Li, take a look please.

I have no idea why the `transform-es2015-classes` happens before my Visitor, can you help please?

### CODE REVIEW

**Comment by nickmessing** [comment]
It doesn't work with this config either:
```json
{
  "plugins": [
    "./index",
    "transform-es2015-modules-commonjs",
    "transform-es2015-classes"
  ],
  "ignore": ["node_modules"]
}
```

So just if the `transform-es2015-classes` is present there it breaks everything

**Comment by nickmessing** [comment]
Works fine, @yyx990803, @QingWei-Li, please review.

**Comment by nickmessing** [comment]
I guess that will be a part of `3.4.0` release so I added that into `README.md`

**Comment by nickmessing** [comment]
We should add a warning to the `README.md` so user doesn't define some other `h` in the methods, that would kill everything.

Actually before this change that would kill everything anyway, but now it's going to show in the transpilation phase (redefining a constant) so I guess that's not an issue.

**Comment by yyx990803** [comment]
Nice work @nickmessing !

One thing I think we should point out in the README is that the auto-injection only works in methods that have proper `this` context - so it wouldn't work in arrow functions and standalone functions. For these two cases, explicitly passing in `h` would still be necessary.

**Comment by nickmessing** [comment]
@yyx990803, well, we can point that it works only in **methods** declared the ES2015 "Method Properties" way, does it sound okay?

**Comment by yyx990803** [comment]
👍  thanks!

**Comment by nickmessing** [comment]
@yyx990803, I just found out that there is a scenario where it won't work:
```
Vue.component('jsx-example', {
  myMethod (num) { // h will not be injected
    return <h1>{num}</h1>
  },
  render () { // h will be injected
    return <div id="foo">{this.myMethod(10)}</div>
  }
})
```
I will fix that asap

**Comment by yyx990803** [comment]
Oops, just released 3.4.0, but I guess that's fine

**Comment by nickmessing** [comment]
That's going to be a bugfix so it's 3.4.1

**Pull request merged**
